#include "WebPortal.h"
#include <WebServer.h>
#include <Update.h>
#include <WiFi.h>
#include <ArduinoJson.h>
static WebServer server(80); static AppConfig *cfg;
static const char PAGE[] PROGMEM=R"HTML(
<!doctype html><meta name=viewport content="width=device-width,initial-scale=1"><title>ESP Usage</title>
<style>body{font:15px system-ui;background:#090c11;color:#edf2f7;max-width:760px;margin:30px auto;padding:18px}section{background:#131820;border:1px solid #2a323d;border-radius:16px;padding:20px;margin:14px 0}h1{font-size:26px}h2{font-size:18px}label{display:block;color:#aeb8c4;margin:12px 0 5px}input{box-sizing:border-box;width:100%;padding:12px;border-radius:9px;border:1px solid #354153;background:#0d1117;color:white}input[type=checkbox]{width:auto}button{padding:12px 18px;border:0;border-radius:9px;background:#10a37f;color:#fff;font-weight:700;margin-top:16px}.warn{color:#f4a62a}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}@media(max-width:600px){.grid{display:block}}</style>
<h1>AI Usage</h1><p>Credentials stay in ESP32 NVS and are never returned by diagnostics.</p>
<form method=post action=/api/config><section><h2>Network</h2><label>Wi-Fi SSID</label><input name=ssid><label>Wi-Fi password (empty keeps current)</label><input name=wifi_pw type=password><label>Hostname</label><input name=host value=espusage></section>
<div class=grid><section><h2>Codex</h2><p class=warn>Requires a trusted adapter; no official consumer Usage API.</p><label><input type=checkbox name=codex_on> Enabled</label><label>HTTPS adapter URL</label><input name=codex_url><label>Adapter bearer token</label><input type=password name=codex_tok></section>
<section><h2>Cursor personal</h2><p class=warn>Unofficial read-only dashboard API; may change.</p><label><input type=checkbox name=cursor_on> Enabled</label><label>Usage URL</label><input name=cursor_url value="https://cursor.com/api/usage-summary"><label>Cursor auth token</label><input type=password name=cursor_tok></section></div>
<section><h2>Display and status</h2><label>Brightness %</label><input name=bright type=number min=1 max=100 value=85><label>Refresh minutes</label><input name=refresh type=number min=1 max=1440 value=5><label>Warning from %</label><input name=warning type=number min=1 max=98 value=70><label>Critical from %</label><input name=critical type=number min=2 max=100 value=90></section><button>Save & restart</button></form>
<section><h2>Firmware update</h2><form method=post action=/api/ota enctype=multipart/form-data><input type=file name=firmware accept=.bin><button>Install OTA</button></form></section>)HTML";
void webBegin(AppConfig &c){cfg=&c;
 server.on("/",HTTP_GET,[]{server.send_P(200,"text/html",PAGE);});
 server.on("/api/status",HTTP_GET,[]{JsonDocument d;d["firmware"]="espusage";d["ip"]=WiFi.localIP().toString();d["rssi"]=WiFi.RSSI();d["uptime_ms"]=millis();d["free_heap"]=ESP.getFreeHeap();d["psram_free"]=ESP.getFreePsram();d["codex_configured"]=cfg->codex.enabled;d["cursor_configured"]=cfg->cursor.enabled;d["warning_percent"]=cfg->warningPercent;d["critical_percent"]=cfg->criticalPercent;String s;serializeJson(d,s);server.send(200,"application/json",s);});
 server.on("/api/health",HTTP_GET,[]{server.send(200,"application/json","{\"ok\":true}");});
 server.on("/api/config",HTTP_POST,[]{cfg->wifiSsid=server.arg("ssid");if(server.arg("wifi_pw").length())cfg->wifiPassword=server.arg("wifi_pw");cfg->hostname=server.arg("host");cfg->codex.enabled=server.hasArg("codex_on");cfg->codex.endpoint=server.arg("codex_url");if(server.arg("codex_tok").length())cfg->codex.token=server.arg("codex_tok");cfg->cursor.enabled=server.hasArg("cursor_on");cfg->cursor.endpoint=server.arg("cursor_url");if(server.arg("cursor_tok").length())cfg->cursor.token=server.arg("cursor_tok");cfg->brightness=constrain(server.arg("bright").toInt(),1,100);cfg->refreshMinutes=constrain(server.arg("refresh").toInt(),1,1440);cfg->warningPercent=constrain(server.arg("warning").toInt(),1,98);cfg->criticalPercent=constrain(server.arg("critical").toInt(),cfg->warningPercent+1,100);saveConfig(*cfg);server.send(200,"text/plain","Saved. Restarting...");delay(400);ESP.restart();});
 server.on("/api/ota",HTTP_POST,[]{bool ok=!Update.hasError();server.send(ok?200:500,"text/plain",ok?"Update complete; restarting":"Update failed");delay(400);if(ok)ESP.restart();},[]{HTTPUpload &u=server.upload();if(u.status==UPLOAD_FILE_START)Update.begin(UPDATE_SIZE_UNKNOWN,U_FLASH);else if(u.status==UPLOAD_FILE_WRITE)Update.write(u.buf,u.currentSize);else if(u.status==UPLOAD_FILE_END)Update.end(true);});server.begin();}
void webLoop(){server.handleClient();}

